apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  interval: 5m
  url: https://repo1.dso.mil/big-bang/apps/third-party/kubevirt.git
  ref:
    tag: 0.58.0-bb.2
  secretRef:
    name: private-git-server
