apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: eck-operator
  namespace: eck-operator
spec:
  interval: 1m
  url: https://github.com/naps-dev/eck-operator.git
  ref:
    name: "###ZARF_CONST_GIT_REF###"