apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dataplane-ek
  namespace: dataplane-ek
spec:
  interval: 5m
  path: "./dataplane-ek/kustomizations/dataplane-ek"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf-cd-pkg
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: dataplane-ek
      name: dataplane-ek
  timeout: 5m
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
      DOMAIN: "###ZARF_VAR_DOMAIN###"
      KIBANA_COUNT: "###ZARF_VAR_KIBANA_COUNT###"
      ES_MASTER_COUNT: "###ZARF_VAR_ES_MASTER_COUNT###"
      ES_DATA_COUNT: "###ZARF_VAR_ES_DATA_COUNT###"
      ES_INGEST_COUNT: "###ZARF_VAR_ES_INGEST_COUNT###"
      ES_ML_COUNT: "###ZARF_VAR_ES_ML_COUNT###"
