apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dataplane-ek
  namespace: dataplane-ek
spec:
  interval: 5m
  url: https://github.com/naps-dev/dataplane-ek
  ref:
    tag: v8.7.1
