apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mixmode-sensor
  namespace: mixmode
spec:
  targetNamespace: mixmode
  releaseName: mixmode-sensor
  interval: 5m
  timeout: 10m
  chart:
    spec:
      interval: 1m
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: mixmode-sensor
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  dependsOn:
    - name: istio
      namespace: bigbang
    - name: dataplane-ek
      namespace: dataplane-ek
    - name: mixmode
      namespace: mixmode
  values:
    mixmodeGlobals: 
      platformHostname: "###ZARF_VAR_PLATFORM_HOSTNAME"
      providerId: "###ZARF_VAR_PROVIDER_ID"
      sensorId: "###ZARF_VAR_SENSOR_ID"
      tenantId: "###ZARF_VAR_TENANT_ID"
      initialApiToken: "###ZARF_VAR_INITIAL_API_TOKEN"
    stenographer.interface: "###ZARF_VAR_CAPTURE_INTERFACE###"
    zeek.interface: "###ZARF_VAR_CAPTURE_INTERFACE###"

