---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 5m
  path: "./metallb/kustomizations/metallb-config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: zarf-cd-pkg
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      namespace: metallb
      name: metallb-config
  timeout: 5m
  postBuild:
    substitute:
      ZARF_REGISTRY: "###ZARF_REGISTRY###"
      ZARF_REGISTRY_AUTH_PULL: "###ZARF_REGISTRY_AUTH_PULL###"
      ZARF_CONST_GIT_REF: "###ZARF_CONST_GIT_REF###"
      IP_ADDRESS_POOL: "###ZARF_VAR_METALLB_IP_ADDRESS_POOL###"
      INTERFACE: "###ZARF_VAR_METALLB_INTERFACE###"
