# SOURCE: https://install.portworx.com/?operator=true&mc=false&kbver=1.26.3&b=true&j=auto&c=px-cluster-0766119b-0327-466f-97db-e74fd3ce231d&stork=true&csi=true&mon=true&tel=false&st=k8s&promop=true
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: px-cluster-0766119b-0327-466f-97db-e74fd3ce231d
  namespace: kube-system
  annotations:
    portworx.io/install-source: "https://install.portworx.com/?operator=true&mc=false&kbver=1.26.3&b=true&j=auto&c=px-cluster-0766119b-0327-466f-97db-e74fd3ce231d&stork=true&csi=true&mon=true&tel=false&st=k8s&promop=true"
spec:
  image: portworx/oci-monitor:2.13.6
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    useAll: true
    journalDevice: auto
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: false
    prometheus:
      enabled: true
      exportMetrics: true
  tolerations:
  - operator: "Exists"
