apiVersion: core.libopenstorage.org/v1
kind: StorageCluster
metadata:
  annotations:
    portworx.io/disable-storage-class: "true"
  name: portworx
  namespace: kube-system
spec:
  image: portworx/oci-monitor:2.13.6
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    useAll: true
    journalDevice: auto
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  autopilot:
    enabled: true
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: false
    prometheus:
      enabled: true
      exportMetrics: true
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  deleteStrategy:
    type: UninstallAndWipe
  placement:
    tolerations:
    - operator: "Exists"


