apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  repl: "1"
  priority_io: high
  io_profile: auto
  stork-volume-provisioner.alpha.kubernetes.io/storage-pool: "1"
allowVolumeExpansion: true
