---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cdi
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: dataplane-ek
  labels:
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: zarf-cd-pkg
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/naps-dev/dco-core.git
  ref:
    name: "###ZARF_CONST_GIT_REF###"
