apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb-config
  namespace: metallb
spec:
  interval: 5m
  url: https://github.com/naps-dev/dco-core.git
  ref:
    name: ${ZARF_CONST_GIT_REF}