apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-config
  namespace: metallb-system
spec:
  targetNamespace: metallb-system
  releaseName: metallb-config
  interval: 5m
  timeout: 10m
  chart:
    spec:
      interval: 1m
      chart: ./metallb/charts/metallb-config
      sourceRef:
        kind: GitRepository
        name: metallb-config
  test:
    enable: false
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 30m
    cleanupOnFail: false
  dependsOn:
    - name: metallb
      namespace: metallb-system
  values:
    ipAddressPool: ${IP_ADDRESS_POOL}
    interface: ${INTERFACE}