apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: dataplane-ek-autoscaler
  namespace: dataplane-ek
spec:
  ## The name of the Elasticsearch cluster to be scaled automatically.
  elasticsearchRef:
    name: dataplane-ek
  ## The autoscaling policies.
  policies:  
    - name: master
      roles:
        - master
      resources:
        nodeCount:
          min: 1
          max: 3
    - name: data
      roles:
        - data
        - ingest
      resources:
        nodeCount:
          min: 1
          max: 15
    - name: ingest
      roles:
        - ingest
      resources:
        nodeCount:
          min: 1
          max: 12
    - name: ml
      roles:
        - ml
      resources:
        nodeCount:
          min: 1
          max: 6
        