apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dataplane-ek
  namespace: dataplane-ek
spec:
  interval: 5m
  url: https://repo1.dso.mil/big-bang/product/packages/elasticsearch-kibana.git
  ref:
    tag: "1.3.1-bb.0"
  secretRef:
    name: private-git-server
