configurations:
  - transformer.yaml

resources:
  - helmrelease.yaml

configMapGenerator:
  - name: dataplane-ek-values
    namespace: dataplane-ek
    behavior: create
    files:
    - values.yaml=values.yaml