
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
hostname: ${DOMAIN}
domain: ${DOMAIN}

istio:
  enabled: true
  kibana:
    gateways:
      - istio-system/dataplane
    hosts:
      - "dataplane-kibana.${DOMAIN}"
  mtls:
    mode: PERMISSIVE

kibana:
  publicBaseUrl: "dataplane-kibana.${DOMAIN}"
  count: ${KIBANA_COUNT}

elastic:
  master:
    count: ${ES_MASTER_COUNT}
  data:
    count: ${ES_DATA_COUNT}