
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
hostname: ${DOMAIN}
domain: ${DOMAIN}

istio:
  enabled: true
  kibana:
    gateways:
      - istio-system/dataplane
    hosts:
      - "dataplane-kibana.${DOMAIN}"
  mtls:
    mode: PERMISSIVE

networkPolicies:
  enabled: false

kibana:
  count: ${KIBANA_COUNT}
  imagePullSecrets:
    - name: private-registry

monitoring:
  enabled: false

metrics:
  enabled: false

elasticsearch:
  imagePullSecrets:
    - name: private-registry
  master:
    enabled: true
    count: ${ES_MASTER_COUNT}
    resources:
      limits:
        cpu: 4
        memory: 32Gi
      requests:
        cpu: 1
        memory: 16Gi
    heap:
      min: 15g
      max: 15g
    initContainers:
      - name: elastic-internal-init-filesystem
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
      - name: elastic-internal-suspend
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
  data:
    enabled: true
    count: ${ES_DATA_COUNT}
    resources:
      limits:
        cpu: 30
        memory: 64Gi
      requests:
        cpu: 12
        memory: 32Gi
    heap:
      min: 31g
      max: 31g
    initContainers:
      - name: elastic-internal-init-filesystem
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
      - name: elastic-internal-suspend
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
  ingest:
    enabled: true
    count: ${ES_INGEST_COUNT}
    resources:
      limits:
        cpu: 20
        memory: 64Gi
      requests:
        cpu: 8
        memory: 32Gi
    heap:
      min: 31g
      max: 31g
    initContainers:
      - name: elastic-internal-init-filesystem
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
      - name: elastic-internal-suspend
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
  ml:
    count: ${ES_ML_COUNT}
    enabled: true
    resources:
      limits:
        cpu: 12
        memory: 50Gi
      requests:
        cpu: 4
        memory: 25Gi
    heap:
      min: 24g
      max: 24g
    initContainers:
      - name: elastic-internal-init-filesystem
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
      - name: elastic-internal-suspend
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
  coord:
    enabled: false
    initContainers:
      - name: elastic-internal-init-filesystem
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
      - name: elastic-internal-suspend
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
