
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
hostname: ${DOMAIN}
domain: ${DOMAIN}

ironbank:
  enabled: false
  
kibana:
  publicBaseUrl: "https://dataplane-kibana.${DOMAIN}"
  count: ${KIBANA_COUNT}

elastic:
  master:
    count: ${ES_MASTER_COUNT}
  data:
    count: ${ES_DATA_COUNT}