
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
hostname: ${DOMAIN}
domain: ${DOMAIN}

ironbank:
  enabled: false
  
kibana:
  publicBaseUrl: "https://dataplane-kibana.${DOMAIN}"

is_production: ${IS_PRODUCTION}