name: Build and Test Arkime
run-name: ${{github.actor}} updated Arkime
on:
  push:
    paths:
      - 'arkime/**'
      - 'test/arkime_package_test.go'
      - '.github/workflows/arkime.yaml'
    tags-ignore: ["v**"]
    branches: ['**']

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
    with:
      component: "arkime"
  
  rebuild-everything:
    needs: [lint]
    uses: ./.github/workflows/rebuild-everything.yaml
    secrets: inherit

  test-arkime:
    needs: [rebuild-everything]
    uses: ./.github/workflows/component-test.yaml
    secrets: inherit
    with:
      component: "arkime"
