name: Build and Deploy Arkime Zarf Package
run-name: ${{github.actor}} is building the Arkime Zarf package
on:
  push:
    paths:
      - 'arkime/**'
      - 'test/arkime_package_test.go'
      - '.github/workflows/arkime.yaml'
    tags-ignore: ["v**"]
    branches: ['**']

permissions:
  id-token: write
  contents: read

jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
    # The REF_NAME is referencing the tag or branch name in the arkime repo (not the dco-core repo)
    # if you're making a change to the capability chart change the REF_NAME to the tag or branch name in the capability repo 
      REF_NAME: "v4.3.2-2"
      REF_TYPE: "tag"
      ZARF_PACKAGE_NAME: zarf-package-arkime-amd64.tar.zst
      IMAGE_TAG: "v4.3.2-2"
      COMPONENT: "arkime"

