name: Component Test
run-name: ${{github.actor}} is testing the ${{ inputs.COMPONENT }} DCO component
on:
  workflow_call:
    inputs:
      COMPONENT:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  packages: write

defaults:
  run:
    shell: bash

env:
  OCI_PATH: "oci://ghcr.io/naps-dev/packages"
  DCO_REF_NAME: "${{ github.head_ref || github.ref_name }}"
  DCO_REF_TYPE: "${{ github.ref_type }}"
  COMPONENT: "${{ inputs.COMPONENT }}"

jobs:
  test-component:
    runs-on: [self-hosted, onprem]
    steps:
      - name: GHCR Login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.5'
          cache: true

      - name: Install dependencies for terratest
        run: |
          go get -t ./...

      - name: Run go test
        working-directory: ./test/
        run: |
          go test -timeout 45m
