name: Build and Deploy DCO Everything Zarf Package
run-name: ${{github.actor}} is building the DCO Everything Zarf package
on:
  push:
    paths:
      - '!**.md'
      - '*/**'
      - 'test/dco_core_package_test.go'
      - '.github/workflows/*.yaml'
  schedule:
    - cron: '30 5 * * *'

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "${{ github.head_ref || github.ref_name }}"
      REF_TYPE: "${{ github.ref_type }}"
      ZARF_PACKAGE: zarf-package-dco-everything-amd64-${{ github.head_ref || github.ref_name }}.tar.zst
      COMPONENT: "dco-everything"
