name: Build and Test DCO Core Components
run-name: ${{github.actor}} updated DCO Core
on:
  push:
    paths:
      - '.github/workflows/component-test.yaml'
      - '.github/workflows/dco-core.yaml'
      - '.github/workflows/lint.yaml'
      - '.github/workflows/rebuild-everything.yaml'
      - 'bigbang/**'
      - 'dataplane-ek/**'
      - 'dco-core/**'
      - 'kubevirt/**'
      - 'metallb/**'
      - 'dataplane-ek/**'
      - 'test/dco_core_package_test.go'
    tags-ignore: ["v**"]
    branches: ['**']

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  lint-1:
    uses: ./.github/workflows/lint.yaml
    with:
      component: "bigbang"  

  lint-2:
    uses: ./.github/workflows/lint.yaml
    with:
      component: "dataplane-ek"

  lint-3:
    uses: ./.github/workflows/lint.yaml
    with:
      component: "dco-core"

  lint-4:
    uses: ./.github/workflows/lint.yaml
    with:
      component: "kubevirt"

  lint-5:
    uses: ./.github/workflows/lint.yaml
    with:
      component: "metallb"

  rebuild-everything:
    needs: [lint-1, lint-2, lint-3, lint-4, lint-5]
    uses: ./.github/workflows/rebuild-everything.yaml
    secrets: inherit

  test-dco-core:
    needs : [rebuild-everything]
    uses: ./.github/workflows/component-test.yaml
    secrets: inherit
    with:
      component: "dco-core"