name: Build DCO Everything Zarf Package
run-name: ${{github.actor}} is building the DCO Everything Zarf package
on:
  workflow_call:

permissions:
  id-token: write
  contents: read
  packages: write

defaults:
  run:
    shell: bash

env:
  OCI_PATH: "oci://ghcr.io/naps-dev/packages"
  REGISTRY: ghcr.io
  ZARF_PACKAGE: zarf-package-dco-everything-amd64-${{ github.head_ref || github.ref_name }}.tar.zst
  REF_NAME: "${{ github.head_ref || github.ref_name }}"
  DCO_REF_TYPE: "${{ github.ref_type }}"
  SKIP_BUILD: false

jobs:
  check-commit-hash:
    runs-on: ubuntu-latest
    outputs:
      skip-build: ${{ steps.check-dco-everything-commit-hash.outputs.SKIP_BUILD }}
    steps:
      # Check commit hash of image in GHCR to see if it has already been built by
      # another workflow as a result of this commit.
      - name: Check DCO Everything commit hash
        id: check-dco-everything-commit-hash
        run: |
          set -euo pipefail
          
          echo "Checking commit hash of DCO Everything image in GHCR"
          
          BEARER=`curl --fail-with-body -u "user:${{ secrets.GITHUB_TOKEN}}" "https://ghcr.io/token?scope=repository:naps-dev/packages/dco-everything:pull" | jq -r ".token"`

          COMMIT_HASH_RAW=`curl -L \
            --fail-with-body \
            -H "Accept: application/vnd.oci.image.manifest.v1+json" \
            -H "Authorization: Bearer ${BEARER}" \
            "https://ghcr.io/v2/naps-dev/packages/dco-everything/manifests/${{ env.REF_NAME }}-amd64" \
            | jq -r '.annotations."org.opencontainers.image.source"'`
          echo "Current commit hash of OCI w/ this tag: $COMMIT_HASH_RAW"
          if [[ ${COMMIT_HASH_RAW} == ${{ github.sha }} ]]; then
            echo "Commit hash matches current commit, skipping build"
            echo "SKIP_BUILD=true" >> $GITHUB_OUTPUT
          fi

  create-package:
    needs: check-commit-hash
    if: needs.check-commit-hash.outputs.skip-build != 'true'
    runs-on: ubuntu-latest
    steps:
      # For pushing Zarf OCI packages
      - name: GHCR Login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.27.0
          download-init-package: true

      # Needed for image pulls only - remove when component images are in GHCR
      - name: Configure AWS ECR Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_ECR_ROLE}}
          role-session-name: arkime-ecr
          aws-region: us-east-1

      # For SOAR Image Pull
      - name: Login to SOAR registry
        run: |
          zarf tools registry login \
            -u "${{secrets.XSOAR_USERNAME}}" \
            -p "${{secrets.XSOAR_PASSWORD}}" \
            "xsoar-registry.pan.dev"

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Login to Registry One
        run: |
          zarf tools registry login \
            -u "${{secrets.REGISTRY1_USERNAME}}" \
            -p "${{secrets.REGISTRY1_PASSWORD}}" \
            "registry1.dso.mil"

      - name: Create Zarf Package from Branch or Tag
        run: |
          # cleanup and init a tmp dir
          rm -rf big-tmp
          mkdir big-tmp

          VAR_GIT_REF=""

          if [[ "${{ env.DCO_REF_TYPE }}" == "branch" ]]; then
            VAR_GIT_REF="refs/heads/${{ env.REF_NAME }}"
          elif [[ "${{ env.DCO_REF_TYPE }}" == "tag" ]]; then
            VAR_GIT_REF="refs/tags/${{ env.REF_NAME }}"
          else
            echo "ERROR: Unknown ref type: ${{ env.DCO_REF_TYPE }}"
            exit 1
          fi
            
          zarf package create --set GIT_REF=${VAR_GIT_REF} \
            --set VERSION=${{ env.REF_NAME }} \
            --set SOURCE=${{ github.sha }} \
            --tmpdir $PWD/big-tmp \
            --skip-sbom \
            --confirm 

          # cleanup tmp dir
          rm -rf ./big-tmp
        working-directory: dco-everything

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/87975021?s=200&v=4
          SLACK_USERNAME: GitHub
          SLACK_TITLE: DCO Everything Zarf Package Built Successfully
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Save Zarf Package to OCI Repo
        run: |
          zarf package publish "${{ env.ZARF_PACKAGE }}" "${{ env.OCI_PATH }}"
        working-directory: dco-everything

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/87975021?s=200&v=4
          SLACK_USERNAME: GitHub
          SLACK_TITLE: DCO Everything Zarf Package Published to ${{ env.REGISTRY }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
